# Config Server 연결 실패 시를 대비한 로컬 백업 설정
server:
  port: 1761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://mm-eureka-server:1761/eureka/