#Config 서버를 통해 정보를 가져오기
spring:
  config:
    import: "optional:configserver:http://localhost:1881"

# Config Server 연결 실패 시를 대비한 로컬 백업 설정
server:
  port: 1761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1761/eureka/